# clean all
# rm -rf install-android5-*

cmake -H. -B./build-android5-stripped-x86 -G'Ninja' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DO_STRIP=1 -DPOCO_STATIC=TRUE -DCMAKE_MAKE_PROGRAM=/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/juangarcia/Library/Android/android-ndk-r19c/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DCMAKE_CXX_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_ABI=x86 -DOPENSSL_CRYPTO_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/x86/libcrypto.a -DOPENSSL_SSL_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/x86/libssl.a -DOPENSSL_USE_STATIC_LIBS=TRUE -DENABLE_NETSSL=TRUE -DOPENSSL_INCLUDE_DIR=/Users/juangarcia/dev/android_openssl/static/include -DCMAKE_INSTALL_PREFIX=install-android5-stripped-x86
cd build-android5-stripped-x86
/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -vC . install
cd ..

cmake -H. -B./build-android5-stripped-x86_64 -G'Ninja' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DO_STRIP=1 -DPOCO_STATIC=TRUE -DCMAKE_MAKE_PROGRAM=/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/juangarcia/Library/Android/android-ndk-r19c/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DCMAKE_CXX_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_ABI=x86_64 -DOPENSSL_CRYPTO_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/x86_64/libcrypto.a -DOPENSSL_SSL_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/x86_64/libssl.a -DOPENSSL_USE_STATIC_LIBS=TRUE -DENABLE_NETSSL=TRUE -DOPENSSL_INCLUDE_DIR=/Users/juangarcia/dev/android_openssl/static/include -DCMAKE_INSTALL_PREFIX=install-android5-stripped-x86_64
cd build-android5-stripped-x86_64
/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -vC . install
cd ..

cmake -H. -B./build-android5-stripped-armeabi-v7a -G'Ninja' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DO_STRIP=1 -DPOCO_STATIC=TRUE -DCMAKE_MAKE_PROGRAM=/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/juangarcia/Library/Android/android-ndk-r19c/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DCMAKE_CXX_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_ABI=armeabi-v7a -DOPENSSL_CRYPTO_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/arm/libcrypto.a -DOPENSSL_SSL_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/arm/libssl.a -DOPENSSL_USE_STATIC_LIBS=TRUE -DENABLE_NETSSL=TRUE -DOPENSSL_INCLUDE_DIR=/Users/juangarcia/dev/android_openssl/static/include -DCMAKE_INSTALL_PREFIX=install-android5-stripped-armeabi-v7a
cd build-android5-stripped-armeabi-v7a
/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -vC . install
cd ..

cmake -H. -B./build-android5-stripped-arm64-v8a -G'Ninja' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DO_STRIP=1 -DPOCO_STATIC=TRUE -DCMAKE_MAKE_PROGRAM=/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/juangarcia/Library/Android/android-ndk-r19c/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DCMAKE_CXX_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_ABI=arm64-v8a -DOPENSSL_CRYPTO_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/arm64/libcrypto.a -DOPENSSL_SSL_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/arm64/libssl.a -DOPENSSL_USE_STATIC_LIBS=TRUE -DENABLE_NETSSL=TRUE -DOPENSSL_INCLUDE_DIR=/Users/juangarcia/dev/android_openssl/static/include -DCMAKE_INSTALL_PREFIX=install-android5-stripped-arm64-v8a
cd build-android5-stripped-arm64-v8a
/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -vC . install
cd ..

cmake -H. -B./build-android5-stripped-x86 -G'Ninja' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DO_STRIP=1 -DCMAKE_MAKE_PROGRAM=/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/juangarcia/Library/Android/android-ndk-r19c/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DCMAKE_CXX_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_ABI=x86 -DOPENSSL_CRYPTO_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/x86/libcrypto.a -DOPENSSL_SSL_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/x86/libssl.a -DOPENSSL_USE_STATIC_LIBS=TRUE -DENABLE_NETSSL=TRUE -DOPENSSL_INCLUDE_DIR=/Users/juangarcia/dev/android_openssl/static/include -DCMAKE_INSTALL_PREFIX=install-android5-stripped-x86
cd build-android5-stripped-x86
/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -vC . install
cd ..

cmake -H. -B./build-android5-stripped-x86_64 -G'Ninja' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DO_STRIP=1 -DCMAKE_MAKE_PROGRAM=/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/juangarcia/Library/Android/android-ndk-r19c/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DCMAKE_CXX_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_ABI=x86_64 -DOPENSSL_CRYPTO_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/x86_64/libcrypto.a -DOPENSSL_SSL_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/x86_64/libssl.a -DOPENSSL_USE_STATIC_LIBS=TRUE -DENABLE_NETSSL=TRUE -DOPENSSL_INCLUDE_DIR=/Users/juangarcia/dev/android_openssl/static/include -DCMAKE_INSTALL_PREFIX=install-android5-stripped-x86_64
cd build-android5-stripped-x86_64
/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -vC . install
cd ..

cmake -H. -B./build-android5-stripped-armeabi-v7a -G'Ninja' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DO_STRIP=1 -DCMAKE_MAKE_PROGRAM=/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/juangarcia/Library/Android/android-ndk-r19c/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DCMAKE_CXX_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_ABI=armeabi-v7a -DOPENSSL_CRYPTO_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/arm/libcrypto.a -DOPENSSL_SSL_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/arm/libssl.a -DOPENSSL_USE_STATIC_LIBS=TRUE -DENABLE_NETSSL=TRUE -DOPENSSL_INCLUDE_DIR=/Users/juangarcia/dev/android_openssl/static/include -DCMAKE_INSTALL_PREFIX=install-android5-stripped-armeabi-v7a
cd build-android5-stripped-armeabi-v7a
/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -vC . install
cd ..

cmake -H. -B./build-android5-stripped-arm64-v8a -G'Ninja' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DO_STRIP=1 -DCMAKE_MAKE_PROGRAM=/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/juangarcia/Library/Android/android-ndk-r19c/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DCMAKE_CXX_COMPILER=/Users/juangarcia/Library/Android/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -DANDROID_NATIVE_API_LEVEL=21 -DANDROID_ABI=arm64-v8a -DOPENSSL_CRYPTO_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/arm64/libcrypto.a -DOPENSSL_SSL_LIBRARY=/Users/juangarcia/dev/android_openssl/static/lib/arm64/libssl.a -DOPENSSL_USE_STATIC_LIBS=TRUE -DENABLE_NETSSL=TRUE -DOPENSSL_INCLUDE_DIR=/Users/juangarcia/dev/android_openssl/static/include -DCMAKE_INSTALL_PREFIX=install-android5-stripped-arm64-v8a
cd build-android5-stripped-arm64-v8a
/Users/juangarcia/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja -vC . install
cd ..
